name: Deploy to Modal
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out your code
      - uses: modalhq/modal-action@v1  # Modal's GitHub Action
        with:
          token: ${{ secrets.MODAL_TOKEN }}
          file: "app.py"  # Path to your Modal entrypoint file
